# Welcome to Jekyll!

# Website settings
title: EVGENGM2024
description: The Official Site for the First Workshop on the Evaluation of Generative Foundation Models
keywords: Generative Foundation Models, Evaluation, CVPRW 
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://evgenfm.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /evgenfm/CVPRW2024/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: EVGENGM2024  # Be used at blog posts' author.
  first_name:   # Be used at index page about me section.
  last_name: EVGENGM2024  # Be used at index page about me section.
  #avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  #github_username: jarrekk  # Leave blank if you don't have now
  #linkedin_id: jarrekk # Leave blank if you don't have now
  #facebook_username: jiakunnj  # Leave blank if you don't have now
  #twitter_username: jiakun614  # Leave blank if you don't have now
  email: zontakm@amazon.com  # Leave blank if you don't have now
  #cv: http://cv.jarrekk.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  desc: 
    <p> <span style="color:red"> Paper submission CMT site is now open! </span> <a href="https://cmt3.research.microsoft.com/EvGenFMCVPR2024" target="_blank"><span class="navy"> https://cmt3.research.microsoft.com/EvGenFMCVPR2024 </span></a><br><br>
    
    The landscape of artificial intelligence is being transformed by the advent of Generative Foundation Models (GenFMs), such as Large Language Models (LLMs) and diffusion models. GenFMs offer unprecedented opportunities to enrich human lives and transform industries. However, they also pose significant challenges, including the generation of factually incorrect or biased information, which might be potentially harmful or misleading. With the emergence of multimodal GenFMs, which leverage and generate content in an increasing number of modalities, these challenges are set to become even more complex. This emphasizes the urgent need for rigorous and effective evaluation methodologies. <br><br>

    The 1st Workshop on Evaluation for Generative Foundation Models at CVPR 2024 aims to build a forum to discuss ongoing efforts in industry and academia, share best practices, and engage the community in working towards more reliable and scalable approaches for GenFMs evaluation. Full CFP can be found at <a href="https://drive.google.com/file/d/1KHTmKhutifDrjP19-NH7KsUmubVWFUeb/view?usp=drive_link" target="_blank"><span class="navy"> CFP link </span></a>.<br><br>

    Papers are limited to eight pages, including figures and tables, in the CVPR style. Additional pages containing only cited references are allowed. Please download the <a href="https://github.com/cvpr-org/author-kit/releases" target="_blank"><span class="navy"> CVPR 2024 Author Kit </span></a> for detailed formatting instructions. <br><br>

    <span style="color:red">Accepted papers will be published as part of CVPR proceeding if camera ready versions are submitted by 4/14. </span><br><br>

    Workshop Time, June 18 2024, 1pm - 6:30pm PDT <br><br></p>




# comment
  disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: EVGENGM2024

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

